### ISSUE TITLE
Handling "batteryNew"

### ISSUE THREAD

**Issue by FauthD** [dArignac/jeelink2mqtt#6]
Hi Alexander,
since running pylacrosse to find the ID after a batterie change is not convenient (and it seems to be abandoned, + does not run in Python 3.12),
I checked if you handle that info somehow.
So far I did not find any log/mqtt message that could expose this info.

I see two options:
1: just a log entry (info), so a "systemctl status jeelink2mqtt.service" would probably enough to see it.
2: publish a separate "new device found" message to mqtt and showing that in HA.

The first option seem easiest to implement. I can do that and send a PR.

LG, Dieter

**Comment by FauthD** [comment]
Will send a PR for 1:
Simple change and helps for now.

**Comment by dArignac** [comment]
I took your code from PR #7 with minor adjustments and committed it - thanks for providing it!
The PR shall then be used for the Ansible script only.
